#!/usr/bin/env sh

commit_msg=$(cat "$1")

pattern="^(init|feat|fix|refactor|docs): .+"

if ! echo "$commit_msg" | grep -Eq "$pattern"; then
  echo "❌ Invalid commit message."
  echo ""
  echo "Use one of:"
  echo "  init: ..."
  echo "  feat: ..."
  echo "  fix: ..."
  echo "  refactor: ..."
  echo "  docs: ..."
  exit 1
fi
